import os
import json
import google.generativeai as genai
from dotenv import load_dotenv
from functools import lru_cache
from .db_handler import log_safety_event, get_weekly_stats

load_dotenv()

def get_api_key():
    return os.getenv("GEMINI_API_KEY")

@lru_cache(maxsize=1)
def get_active_model_name():
    try:
        api_key = get_api_key()
        if not api_key: return "gemini-pro"
        
        genai.configure(api_key=api_key)
        models = genai.list_models()
        candidates = []
        for m in models:
            if "generateContent" in m.supported_generation_methods:
                name = m.name.replace("models/", "")
                candidates.append(name)
        
        preferred = ["gemini-1.5-flash", "gemini-1.5-pro", "gemini-pro"]
        for pref in preferred:
            if pref in candidates:
                return pref
        return candidates[0] if candidates else "gemini-pro"
    except:
        return "gemini-pro"

def get_gemini_response(context_text, crop_type, role="Smart Farming Expert"):
    api_key = get_api_key()
    if not api_key:
        return "Error: API Key not found. Please set GEMINI_API_KEY in .env"

    try:
        genai.configure(api_key=api_key)
        model = genai.GenerativeModel(get_active_model_name())
        
        # SAFETY: Strict System Prompt for Legal Compliance
        system_safety_prompt = """
        IMPORTANT SAFETY & LEGAL RULES:
        1. YOU ARE AN ASSISTANT, NOT A LICENSED AGRONOMIST.
        2. DO NOT RECOMMEND SPECIFIC CHEMICAL PESTICIDE BRAND NAMES.
        3. Suggest only CULTURAL (e.g., ventilation), MECHANICAL (e.g., traps), or BIOLOGICAL controls.
        4. ALWAYS advise user to consult local extension services.
        5. Use soft language: "Consider", "Might help", "Monitor".
        """
        
        prompt = f"""
        {system_safety_prompt}
        
        You are {role}, also known as ForHuman AI.
        Current Crop: {crop_type}
        
        Analyze the following real-time data and provide a specific "Ag-Prescription".
        
        DATA:
        {context_text}
        
        OUTPUT FORMAT:
        **Status**: [Normal / Warning / Critical]
        **Prescription**: [Specific action, e.g., "Irrigate 15 mins", "Ventilate"]
        **Reasoning**: [Explain why based on data and crop needs]
        
        Keep it brief, professional, and actionable for a US farmer. Use Imperial units.
        
        [DISCLAIMER]: This is an AI-generated suggestion for informational purposes only. Consult a professional before taking action.
        """
        
        response = model.generate_content(prompt)
        final_text = response.text
        disclaimer = "\n\n[MANDATORY DISCLAIMER]: This analysis is generated by AI for informational purposes only. It is NOT a professional diagnosis. Always consult a certified agricultural professional."
        if "[DISCLAIMER]" not in final_text:
            final_text += disclaimer
        return final_text
    except Exception as e:
        # Fallback simulation
        return f"""
        **Status**: Normal (Simulation Mode)
        **Prescription**: Maintain current irrigation schedule.
        **Reasoning**: Conditions are within expected ranges for {crop_type}. 
        *(Error: {str(e)})*
        
        [DISCLAIMER]: This is a simulated response.
        """

def load_knowledge_base():
    try:
        base_path = os.path.dirname(__file__)
        path = os.path.join(base_path, 'knowledge_base.json')
        with open(path, 'r') as f:
            return json.load(f)
    except Exception as e:
        print(f"Error loading KB: {e}")
        return {}

def analyze_situation(weather, crop_type):
    kb = load_knowledge_base()
    crop_info = kb.get(crop_type, {})
    
    context = f"""
    [Situation Report]
    Crop: {crop_type}
    Weather: {weather['temperature']}F, {weather['humidity']}%, Rain: {weather['rain']}in, Wind: {weather['wind_speed']}mph
    
    [Optimal Ranges]
    Temp: {crop_info.get('temp_min')}-{crop_info.get('temp_max')}F
    Humidity: {crop_info.get('humidity_min')}-{crop_info.get('humidity_max')}%
    """
    
    return get_gemini_response(context, crop_type, role="US Agricultural Extension Agent")

def generate_weekly_report(crop_type):
    stats = get_weekly_stats(crop_type)
    if not stats:
        return "Insufficient data to generate weekly report."
        
    kb = load_knowledge_base()
    crop_info = kb.get(crop_type, {})
    
    # Prompt for AI Report
    context = f"""
    [Weekly Farm Stats for {crop_type}]
    Avg Temp: {stats.get('avg_temp')}
    Avg Moisture: {stats.get('avg_moisture')}%
    Data Points Collected: {stats.get('data_points')}
    
    [Standard Info]
    Target Moisture: {crop_info.get('soil_moisture_min')} - {crop_info.get('soil_moisture_max')}%
    """
    
    api_key = get_api_key()
    if not api_key:
        return f"Weekly Report (Simulated): Stats indicate stable growth. Avg Temp {stats.get('avg_temp')}."
        
    try:
        genai.configure(api_key=api_key)
        model = genai.GenerativeModel("gemini-1.5-flash")
        
        # SAFETY PROMPT
        system_safety_prompt = """
        IMPORTANT LEGAL DISCLAIMER:
        You are an AI assistant. Do NOT provide binding professional advice.
        Focus on trends and data analysis.
        DO NOT recommend chemical treatments.
        """
        
        prompt = f"""
        {system_safety_prompt}
        
        You are a Farm Manager AI. Write a 'Weekly Farm Report' based on the stats.
        Stats: {context}
        
        Output Structure:
        1. **Grade**: (A, B, C, etc based on adherence to standards)
        2. **Summary**: What went well/wrong.
        3. **Next Week Advice**: Focus area.
        
        Examples of Advice: "Maintain humidity", "Watch for temperature drops", "Check irrigation".
        
        [DISCLAIMER]: This report is AI-generated based on user data. Verify all conditions manually.
        """
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        return f"Error creating report: {e}"

def analyze_crop_image(image_data):
    api_key = get_api_key()
    if not api_key:
        return "Error: API Key not found."
        
    try:
        genai.configure(api_key=api_key)
        model_name = get_active_model_name()
        # Ensure model supports vision
        if "flash" not in model_name and "1.5" not in model_name:
            model_name = "gemini-1.5-flash"
            
        model = genai.GenerativeModel(model_name)
        
        prompt = """
        IMPORTANT LEGAL & SAFETY CHECK:
        1. YOU ARE AN AI ASSISTANT, NOT A PLANT PATHOLOGIST.
        2. Identify the crop.
        3. Suggest POTENTIAL causes for symptoms (e.g., "This resembles powdery mildew").
        4. Recommend NON-CHEMICAL controls (removing leaves, improving airflow).
        5. DO NOT PRESCRIBE SPECIFIC FUNGICIDES OR PESTICIDES.
        6. Always advise consulting a local expert.

        Task:
        1. Identify the crop.
        2. Diagnose potential issues.
        3. Recommend safe management practices.
        
        If healthy, say "Healthy" and estimate yield potential.
        
        [DISCLAIMER]: This analysis is for informational purposes only and is not a professional diagnosis.
        """
        

        response = model.generate_content([prompt, image_data])
        final_text = response.text
        disclaimer = "\n\n[MANDATORY DISCLAIMER]: This analysis is generated by AI for informational purposes only. It is NOT a professional diagnosis and should not be used as a basis for chemical treatment or financial decisions. Always consult a certified agricultural extension agent."
        if "[DISCLAIMER]" not in final_text:
            final_text += disclaimer
        return final_text
    except Exception as e:
        return f"Global API Error: {str(e)}"

def analyze_pest_risk_with_ai(weather_forecast, crop_type):
    api_key = get_api_key()
    if not api_key:
        return []

    try:
        genai.configure(api_key=api_key)
        model = genai.GenerativeModel("gemini-1.5-flash")
        
        prompt = f"""
        You are an expert plant pathologist. 
        Analyze the pest/disease risk for {crop_type} based on this 7-day weather forecast.
        
        FORECAST:
        {json.dumps(weather_forecast)}
        
        Return a JSON ARRAY of 7 objects.
        Do NOT use markdown code blocks. Just return the raw JSON.
        
        JSON Structure:
        [
            {{
                "Date": "YYYY-MM-DD",
                "Risk Score": 0-100 (integer),
                "Condition": "High/Medium/Low Risk: [Specific Name]",
                "Pest": "[Primary Pest Name]"
            }}
        ]
        """
        
        response = model.generate_content(prompt)
        text = response.text.strip()
        
        # Robust Clean & Parse
        try:
            # Remove any markdown wrapping if present
            text = text.replace("```json", "").replace("```", "").strip()
            
            import re
            match = re.search(r'\[.*\]', text, re.DOTALL)
            if match:
                return json.loads(match.group())
            return json.loads(text)
        except Exception as e:
            print(f"AI Pest Parse Error: {e} | Raw: {text[:50]}...")
            return []
    except Exception as e:
        print(f"AI Pest General Error: {e}")
        return []

def analyze_market_prices_with_ai(crop_type):
    api_key = get_api_key()
    if not api_key:
        return generate_fallback_market_data()

    try:
        genai.configure(api_key=api_key)
        model = genai.GenerativeModel("gemini-1.5-flash")
        
        prompt = f"""
        You are an agricultural market expert.
        Estimate the wholesale prices ($/lb) for {crop_type} in the US market for the PAST 7 DAYS (ending today).
        
        Return a JSON ARRAY of 7 objects.
        Do NOT use markdown code blocks. Just return the raw JSON.
        
        JSON Structure:
        [
            {{
                "Date": "YYYY-MM-DD",
                "Price ($/lb)": 0.00 (float)
            }}
        ]
        """
        
        response = model.generate_content(prompt)
        text = response.text.strip()
        
        try:
            # Remove any markdown wrapping if present
            text = text.replace("```json", "").replace("```", "").strip()
            
            import re
            match = re.search(r'\[.*\]', text, re.DOTALL)
            if match:
                return json.loads(match.group())
            return json.loads(text)
        except Exception as e:
            print(f"AI Market Parse Error: {e} | Raw: {text[:50]}...")
            return []
    except Exception as e:
        print(f"AI Market General Error: {e}")
        # Fallback to estimated data instead of empty
        return generate_fallback_market_data()

def generate_fallback_market_data():
    from datetime import datetime, timedelta
    import random
    
    data = []
    base_price = 2.50
    today = datetime.now()
    
    for i in range(7):
        date = (today - timedelta(days=6-i)).strftime("%Y-%m-%d")
        # Random fluctuation +/- 5%
        fluctuation = base_price * (random.uniform(-0.05, 0.05))
        price = round(base_price + fluctuation, 2)
        data.append({
            "Date": date,
            "Price ($/lb)": price
        })
    return data
